version: "3.9"

services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3005:3000"
    image: lib-t3
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/libdb?schema=public
    depends_on:
      - db 
    networks:
      - lib-net

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=libdb
    networks:
      - lib-net
    volumes:
      - lib:/var/lib/postgresql

networks:
  lib-net:
volumes: 
  lib: